spring.application.name=boundless-books
<<<<<<< HEAD
spring.datasource.url=jdbc:mysql://inventoryaws-db.cviqa0w8kgab.us-east-2.rds.amazonaws.com:3306/boundless_books
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}

=======
spring.datasource.url=jdbc:mysql://127.0.0.1:8889/boundless_books?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC# REPLACE the two placeholder values below with your MySQL Workbench login.
spring.datasource.username=username
spring.datasource.password=password
>>>>>>> branch 'main' of https://github.com/Wilkeaustin/boundless-books.git
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.thymeleaf.cache=false
server.port=8080
